# Generated by Django 6.0 on 2025-12-15 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strawandstroke_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
